version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install dpkg, fakeroot and rpm
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot rpm

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn make

      - store_artifacts:
          path: ~/repo/out/make

publish-github-release:
  docker:
    - image: circleci/golang:1.8
  steps:
    - attach_workspace:
        at: ~/repo/out/make
    - run:
        name: "Publish Release on GitHub"
        command:
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ~/repo/out/make
