version: 2.1
orbs:
  github-release: duffn/github-release@0.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install dpkg, fakeroot and rpm
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot rpm

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn make

      - store_artifacts:
          path: ~/repo/out/make
      - run:
          name: "release"
          command: |
           curl -X POST \
            --upload-file "~/repo/out/make/deb/x64/go-laptop-setup_0.1.0_amd64.deb" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \ 
            https://uploads.github.com/repos/gogosoon/go-laptop-setup/releases/0.1.0/assets?name=soft.deb


  publish:
    docker:
      - image: cimg/go:1.19.0
    steps:
      - attach_workspace:
          at: ~/repo/out/make
      - run:
          name: "Publish Release on GitHub"
          command: |
            go install github.com/tcnksm/ghr@latest
            
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete 0.1.0 ./go-laptop-setup_0.1.0_amd64.deb

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
