name: Node.js CI
on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
          node-version: '16.x'
     - name: Install dependencies
       run: yarn
     - name: Make build
       run: yarn make
     - name: Create Release
       uses: actions/create-release@v1
       with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}