name: Node.js CI
on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
          node-version: '16.x'
     - name: Install dependencies
       run: yarn
     - name: Make build
       run: yarn make
     - name: Read package.json
       uses: dutscher/read-package-json-endpoint-actions@v1.33.7
       id: package-json-endpoint
     - name: Create Release
       uses: ncipollo/release-action@v1
       with: 
          allowUpdates: true
          artifacts: "./out/make/deb/x64*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-json-endpoint.outputs.version }}